name: Compilation & tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  job_build_debug:
    name: Build debug
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:2.0.0-1

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Boilerplate plugin
        run: |
          make DEBUG=1

      - name: Upload Boilerplate binary
        uses: actions/upload-artifact@v2
        with:
          name: boilerplate-app-debug
          path: bin
