name: Compilation & tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop


jobs:
  job_nano_build:
    name: Build plugin
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
            name: nanos
          - SDK: "$NANOX_SDK"
            name: nanox
          - SDK: "$NANOSP_SDK"
            name: nanosp
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          make BOLOS_SDK=${{ matrix.SDK }}
          mv bin/app.elf plugin_${{ matrix.name }}.elf

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: alkemi_${{ matrix.name }}_plugin
          path: ./*.elf

  job-e2e-tests:
    name: E2E tests for NanoS, X and S+
    needs: [job_nano_build]
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install APT dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.0"

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Install JS dependencies
        run: |
          cd tests && yarn install

      - name: Download app binary
        uses: actions/download-artifact@v2

      - name: Gather all artifacts
        run: |
          mv *_plugin/*.elf tests/elfs

      - name: Run zemu tests
        run: |
          cd tests && yarn test
